name: 'CI'
on: [push, pull_request]
jobs:
  test:
    name: Test (go ${{matrix.go}})
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        go: ['1.18', '1.19', '1.20', '1.21', '1.22', '1.23', '1.24', '1.25', '1.26']
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
      with:
        go-version: ${{ matrix.go }}
    - run: make test

  test-integration:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - uses: azure/setup-kubectl@829323503d1be3d00ca8346e5391ca0b07a9ab0d # v5.1.0
    - uses: azure/setup-helm@vdda3372f752e03dde6b3237bc9431cdc2f7a02a2 # v5.0.0
      with:
        version: v3.21.0
    - uses: engineerd/setup-kind@71e45b960fc8dd50b4aeabf6eb6ef2ca0920b4c1 # v0.6.2
      with:
        version: "v0.17.0" # Version of Kind to use
    - run: |
        helm repo add bitnami https://charts.bitnami.com/bitnami
        helm repo add stable https://charts.helm.sh/stable
        helm repo update
    - uses: ./.
      with:
        release-name: 'test-release'
        chart: 'bitnami/nginx'
        namespace: test-namespace
        create-namespace: true
        debug: true
        wait: true
        timeout: 10m
        sets: >
          service.type=ClusterIP
          myValue=test
    - if: failure()
      run: |
        kubectl config set-context kind-kind --namespace test-namespace
        kubectl get pods
        echo "==========================="
        kubectl get pods --no-headers | awk '{print $1}' | xargs -L 1 kubectl logs
